#
# This file is part of GEO-Knowledge-Hub-CMS.
#
# Copyright (C) 2023 GEO Secretariat.
#
# GEO-Knowledge-Hub-CMS is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

version: '3'
services:
  geo-knowledge-hub-cms-backend-db:
    container_name: geo-knowledge-hub-cms-backend-db
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5432:5432'
